#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  2 23:53:34 2018

@author: gautam

A regular polygon has n number of sides. Each side has length s.

    The area of a regular polygon is: 

    The perimeter of a polygon is: length of the boundary of the polygon

Write a function called polysum that takes 2 arguments, n and s. 
This function should sum the area and square of the perimeter of the regular polygon.
 The function returns the sum, rounded to 4 decimal places.
"""
import math
def polysum(n,s):
    area = (0.25 * n * s*s)/math.tan(math.pi/n)
    perimiter = n*s
    #print  (round(area + perimiter**2, 4))
    return round(area+perimiter**2, 4)
    

