#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 24 09:26:24 2018

@author: gautam
"""

x=25
epsilon = 0.01
num_guesses=0
low=1.0
high=x
ans = (low + high)/2.0

while(abs(ans**2-x)>= epsilon):
    print('low= '+str(low) + ' high = '+str(high) +' ans= '+str(ans))
    num_guesses +=1
    if(ans**2 < x):
        low=ans
    else:
        high =ans
    ans = (high + low)/2.0
    
print('num_guesses= '+str(num_guesses))
print(str(ans)+'is close to squre root of ' +str(x))

"""
x=25
epsilon = 0.01
num_guesses=0
low=1.0
high=x
ans = (low + high)/2.0

while(abs(ans**2 -x) >= epsilon):
    print ("low = "+str(low)+ " high " +str(high) + " ans = " +str(ans))
    num_guesses +=1
    if(ans**2 < x):
        low = ans
    else:
        hign = ans
        
    ans = (low + high)/2
    
print(num_guesses)
print(str(ans) + "is close to squareroot of "+str(x))
"""          
        






x=27
epsilon = 0.01
num_guesses=0
low=1.0
high=x
ans = (low + high)/2.0

while(abs(ans**3-x)>= epsilon):
    print('low= '+str(low) + ' high = '+str(high) +' ans= '+str(ans))
    num_guesses +=1
    if(ans**3 < x):
        low=ans
    else:
        high =ans
    ans = (high + low)/2.0
    
print('num_guesses= '+str(num_guesses))
print(str(ans)+'is close to squre root of ' +str(x))
    