#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 24 08:40:32 2018

@author: gautam
"""

cube = 27
epsilon = 0.01
guess = 0.0
increment = 0.0001
num_guesses = 0

while(abs(guess**3 - cube ) >= epsilon):
    guess += increment
    num_guesses +=1
print('num_guesses=', num_guesses)
if(abs(guess**3 - cube) >= epsilon):
    print('failed on cube root of', cube)
else:
    print(guess , "is close to the cube root of", cube)
