#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 18 22:32:24 2018

@author: gautam
"""

x = int(input('enter a number:'))
ans = 0
while ans**3 < abs(x):
    ans = ans+1
if(ans**3 !=abs(x)):
    print(str(x) + 'is not a perfect cube')
else:
    if(x<0):
        ans = -ans
    print('cube root of '+str(x)+ ' is ' +str(ans))