#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 25 09:14:25 2018

@author: gautam
"""

num = 11


result = ''

if num == 0:
    result = '0'

while (num > 0):
    result = str(num%2)+result
    num = num//2
 
print(result)
    
    