#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 25 08:20:02 2018

@author: gautam
"""

high = 100
low = 0

print("please think of a number between {0} and {1} !".format(low, high))

guessing = True
while guessing:
    guess = abs((low + high)//2)
    print("is your secret number {0}".format(guess))
    pointer = input("Enter 'h' to indicate the guess is too high.  Enter 'l'   to   indicate the guess is too low. Enter 'c' to indicate I guessed correctly.").lower()
     
    if(pointer == 'h'):
         high = guess
         
    
    elif(pointer == 'l'):
        low = guess
        
        
    elif(pointer =='c'):
        guessing= False
        
    else:
        print("sorry i didnot understand your input")
        
print("Game over. Your secret number was: {0}".format(guess))
        
    