#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 27 23:32:43 2018

@author: gautam
"""

def g(x):
    def h():
        x = 'abc'
    x = x+1
    print('in g(x): x = ', x)
    h()
    return x
x=3

