#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 18 22:53:52 2018

@author: gautam
"""

s = 'azcbobobegghakl'
total=0

for letter in s:
    if letter in "aeiouAEIOU":
        total = total +1
print(total)


t = 'azcbobobegghakl'
u='bob'
totall= 0

if u in t:
    totall = totall +1
print(totall)
    
        