#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 19 20:49:48 2018

@author: gautam
"""

s = 'bobbbobobsbgbooboo'
numBobs = 0
for i in range(1, len(s)-2):
    if s[i]+s[i+1]+s[i+2] == 'bob':
        numBobs += 1
print ('Number of times bob occurs is:'+ str(numBobs))