#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  8 23:13:25 2018

@author: gautam
"""

"""

Write a procedure called oddTuples, which takes a tuple as input, and returns a new tuple as 
output, where every other element of the input tuple is copied, starting with the first one. 
So if test is the tuple ('I', 'am', 'a', 'test', 'tuple'), then evaluating oddTuples on this 
input would return the tuple ('I', 'a', 'tuple'). 
"""

def oddTuples(aTup):
    '''
    aTup: a tuple
    
    returns: tuple, every other element of aTup. 
    '''
    # Your Code Here
    resultTup = ()
    otherResult = ()
    i=0
    for index in aTup:
        if i%2 == 0:
            resultTup += (index,)
            otherResult += (aTup[index],)
        i+=1
    return resultTup, otherResult
    
    

