#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  1 02:34:48 2018

@author: gautam
"""

def isPelindrome(s):
    def toChars(s):
        ans =''
        for c in 'abcdefghijklmnopqrstuvwxyz':
            ans = ans + c
        return ans;
    def isPal(s):
        if len(s<= 1):
            return True
        else:
            return s[0]==s[-1] and isPal(s[1:-1])