#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 27 22:27:07 2018

@author: gautam
"""

# solution is [g -(polinomial) x (first derivative of the the polynomial equation)]


#newton raphson methon

epsilon =0.01;
y = 54.0;
guess = y/2.0
numGuess =0;


while abs( guess*guess -y) >= epsilon:
    numGuess +=1
    guess = guess - (((guess**2) - y)/(2*guess))
    
print('numGuess = '+str(numGuess))
print("square root of "+str(y)+"is about "+str(guess))

    