#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 27 23:56:34 2018

@author: gautam
"""

def a(x, y, z):
     if x:
         return y
     else:
         return z

def b(q, r):
    return a(q>r, q, r)



def foo(x, y = 5):
   def bar(x):
      return x + 1
   return bar(y * 2)
          
