#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  8 22:39:30 2018

@author: gautam
"""

"""
t = (1,2,3,4,5,6)
singleton_tuple = (t[0], ) 

"""

def get_data(aTuple) :
    nums = ()
    words = ()
    for t in aTuple:
        nums = nums + (t[0],)
        print('1')
        if t[1] not in words:
            words = words + (t[1],)
            
        print(words)
        print(len(aTuple))
            
        min_nums = min(nums)
        max_nums = max(nums)
        unique_word = len(words)
        return (min_nums, max_nums, unique_word)
    
    
#call the method

(small , large, words) = get_data(((1,'mine'),
                                  (3,'yours'),
                                  (5,'ours'),
                                  (7,'mine')))