#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  8 23:09:00 2018

@author: gautam
"""

x = (1, 2, (3, 'John', 4), 'Hi')
x[0]  = 8

# cant do this as 
#TypeError: 'tuple' object does not support item assignment